### ISSUE TITLE
Miss KlineSort

### ISSUE THREAD

**Issue by DongfengXu** [maisuid/madaoQT#4]
https://github.com/maisuid/madaoQT/blob/9072976c71f3bcc4197c25b35e2edd7fe93b420b/exchange/ctpdll.go#L56

**Comment by maisuid** [comment]
type KlineSort []KlineValue

func (p KlineSort) Len() int           { return len(p) }
func (p KlineSort) Swap(i, j int)      { p[i], p[j] = p[j], p[i] }
func (p KlineSort) Less(i, j int) bool { return p[i].OpenTime < p[j].OpenTime }

只是一个排序，晚点会提交

**Comment by maisuid** [comment]
updated:
https://github.com/maisuid/madaoQT/commit/b9c1bf091949f816ffdd866a8382dfd528895598
